import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { API_URL, fromImageToUrl } from "../utils/urls";
import Link from "next/link";
import { twoDecimals } from "../utils/format";

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {products.map((product) => (
        <div key={product.name} className={styles.product}>
          <Link href={`/products/${product.slug}`}>
            <a>
              <div className={styles.product__row}>
                <div className={styles.product__colimg}>
                  <img src={fromImageToUrl(product.image)} />
                </div>
                <div className={styles.product__col}>
                  {product.name} ${twoDecimals(product.price)}
                </div>
              </div>
            </a>
          </Link>
        </div>
      ))}
    </div>
  );
}

export async function getStaticProps() {
  //fetch the products
  const product_res = await fetch(`${API_URL}/products`);
  const products = await product_res.json();

  return { props: { products } };
}
